### ISSUE TITLE
bash scripts/stn_att_rec.sh

### ISSUE THREAD

**Issue by happy20200** [ayumiymk/aster.pytorch#56]
bash scripts/stn_att_rec.sh                                                                                                              [1]
using cuda.
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    main(args)
  File "main.py", line 106, in main
    make_symlink_if_not_exists(osp.join(args.real_logs_dir, args.logs_dir), osp.dirname(osp.normpath(args.logs_dir)))
  File "/home/yyk/Downloads/aster.pytorch-master/lib/utils/osutils.py", line 20, in make_symlink_if_not_exists
    os.makedirs(real_path)
  File "/opt/anaconda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/anaconda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/anaconda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "/opt/anaconda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
please help ！

**Comment by ayumiymk** [comment]
You don't have the permission to new a folder under './data'
